### ISSUE TITLE
Feature/session-storage

### ISSUE THREAD

**Issue by alessandro-canonico** [develhope/FS25-Team2-Project4#22]
- [x] Add selected ingredient to session storage
- [x] Remove session storage when logout

**Comment by IlyasMacaluso** [comment]
Al login -> aggiunto authToken al localStorage per autenticare l'utente
al logout -> rimosso authToken dal localStorage per rimuovere l'autenticazione
(oltre ad impostare isAuthenticated a true/false)

non abbiamo dati da eliminare in sessionStorage al momento, vedremo andando avanti se ce ne saranno da eliminare al logout.
