### ISSUE TITLE
Feature/filters

### ISSUE THREAD

**Issue by alessandro-canonico** [develhope/FS25-Team2-Project4#5]
- [x] #12
- [x] Create button filter component (2)
- [ ] Implement style

(1)
![switch](https://github.com/develhope/FS25-Team2-Project4/assets/158085680/67638141-6c94-4309-8c1c-85ced0d8d349)

(2)
![filter-chip](https://github.com/develhope/FS25-Team2-Project4/assets/158085680/203473e4-1bdd-4ada-9b92-0eac3e474542)

**Comment by framelad** [comment]
creato PopupFilter che gestisce in autonomia la lista degli switch, per ogni categoria di Filtri
