### ISSUE TITLE
Feature/Navigation-bar

### ISSUE THREAD

**Issue by alessandro-canonico** [develhope/FS25-Team2-Project4#6]
- [x] Create Nav-bar component
- [x] Create Nav-bar button component
- [x] Implement Style Nav-bar
- [x] Implement Style nav-bar button

**Comment by framelad** [comment]
guarda questa libreria per semplificare la navigazione
https://reactnavigation.org/docs/getting-started

**Comment by Andre-23889** [comment]
ho  modificato il file App, adesso raccogliere Routes:
per ora c'è solo una route, che manda ad una pagina vuota ma i bottoni della navbar creano dei link a tre pagine: 
/discovery (dove credo si dovrrà visualizzare la pagina degli ingredienti random)
/favorited (per ora è un link anchde questo, se vorrete visualizzare i favoriti come un popup invece che come pagina, implementerò le modifiche quando )
/account 
mancano le route assegnate a quedsti indirizzi in App, perchè per ora non so se c'è qualcosa da renderizzare.
